### PR TITLE
General message clarifications

### PR DESCRIPTION
**Pull request by systemcrash**

### CODE REVIEW

**Comment by systemcrash** [comment]
These are changes to make many GUI messages more intelligible. They're currently confusing, ambiguous, or need some grammar love :)

**Comment by nemunaire** [comment]
Hello @systemcrash!

Thanks for your contribution!

Like many other open source projects, we need you to complete a [Contributor License Agreement (“CLA”)](http://en.wikipedia.org/wiki/Contributor_license_agreement).

Note that the following agreement is not a transfer of copyright ownership. You also do not change your rights to use your own contributions for any other purpose. The goal is to protect both the contributor and the happyDNS team behind the project. It also gives us the option to relicense the code with a more permissive license in the future.

Don't hesitate to ask us any questions regarding this CLA at contributors AT happydomain DOT org.

Please fill out the [online form](https://git.happydomain.org/CLA).

**Comment by systemcrash** [comment]
Sure - I can sign. I think https://cla-assistant.io/ gives a smoother experience, especially for those already on github - for future reference.

**Comment by nemunaire** [comment]
This is a huge task you did here. We highly appreciate your review :heart:

**Comment by nemunaire** [comment]
Merged as fd8876da75b940a88c29e816cd3078115a1f6043

BTW thanks for the tip about cla-assistant.io, we'll look into it!

**Pull request closed without merging**
